// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6R_qmkIvPlOjuEyLSNwtznLAFpBleeQ',
    appId: '1:954600539446:web:0540950fb462ce9c98df97',
    messagingSenderId: '954600539446',
    projectId: 'mobile-final-3838c',
    authDomain: 'mobile-final-3838c.firebaseapp.com',
    storageBucket: 'mobile-final-3838c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIUYA2NPF4QUBSvT8AQ4wfA47V2OAcco',
    appId: '1:954600539446:android:4d7285b9dfa0191e98df97',
    messagingSenderId: '954600539446',
    projectId: 'mobile-final-3838c',
    storageBucket: 'mobile-final-3838c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTWbGGVJM5vYzX_E4qOOsbHb0S-eXosR8',
    appId: '1:954600539446:ios:383ccb8bb998dd3498df97',
    messagingSenderId: '954600539446',
    projectId: 'mobile-final-3838c',
    storageBucket: 'mobile-final-3838c.firebasestorage.app',
    iosBundleId: 'com.example.mobileFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTWbGGVJM5vYzX_E4qOOsbHb0S-eXosR8',
    appId: '1:954600539446:ios:383ccb8bb998dd3498df97',
    messagingSenderId: '954600539446',
    projectId: 'mobile-final-3838c',
    storageBucket: 'mobile-final-3838c.firebasestorage.app',
    iosBundleId: 'com.example.mobileFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo6R_qmkIvPlOjuEyLSNwtznLAFpBleeQ',
    appId: '1:954600539446:web:a994e2223fa576dc98df97',
    messagingSenderId: '954600539446',
    projectId: 'mobile-final-3838c',
    authDomain: 'mobile-final-3838c.firebaseapp.com',
    storageBucket: 'mobile-final-3838c.firebasestorage.app',
  );
}
